name: Intermediate environment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # コンテキストの値を、環境変数ACTORにセット
    steps:
      - run: echo "${ACTOR}" #　環境変数ACTORの値を表示
