name: Variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME_LOCAL: ${{ vars.USERNAME }} # varsコンテキストUSERNAMEの値を、環境変数USERNAMEにセット
    steps:
      - run: echo "${USERNAME_LOCAL}" # 環境変数USERNAMEの値(Variables)を表示
