name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}     # 第一引数が第二引数を含んでいたら true
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }} # 第一引数が第二引数で始まっていたら true
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}     # 第一引数が第二引数で終わっていたら true