name: Variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.actor }} # varsコンテキストactorの値を、環境変数USERNAMEにセット
    steps:
      - run: echo "${USERNAME}" # 環境変数USERNAMEの値(Variables)を表示
