name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD_LOCAL: ${{ secrets.PASSWORD}}   # secretsコンテキストに、GitHubに設定されているSecretsの環境変数がある
    steps:
      - run: echo "${PASSWORD_LOCAL}"                  # ログ出力はマスクされる
      - run: echo "${PASSWORD_LOCAL:0:1} ${PASSWORD_LOCAL#?}" # ログ出力はマスクされない